name: Update NZ Time JSON

on:
  schedule:
    - cron: '*/1 * * * *' # every 1 minute
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set NZ time
        run: |
          mkdir -p .tmp
          TZ="Pacific/Auckland" date +"%H:%M" > .tmp/time.txt
          echo "{ \"time\": \"$(cat .tmp/time.txt)\" }" > time.json

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add time.json
          git commit -m "Update NZ time"
          git push
